doodle/doodle/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'doodle.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^poll/', include('poll.urls', namespace="poll")),
    url(r'^users/', include('users.urls', namespace="users")),
)

doodle/poll/urls.py
from django.conf.urls import patterns, url
from poll import views

urlpatterns = patterns('',
        url(r'^$', views.IndexView.as_view(), name='index'),
        url(r'^(?P<pk>\d+)/$', views.ResultsView.as_view(), name='detail'),
        url(r'^(?P<pk>\d+)/vote/$', views.VoteView.as_view(), name='vote'),
        url(r'^(?P<pk>\d+)/edit/(?P<admin_key>.+)/$', views.EditView.as_view(), name='edit'),
        url(r'^(?P<pk>\d+)/addTime/(?P<admin_key>.+)/$', views.AddTimeView.as_view(), name='add_time'),
        url(r'^(?P<pk>\d+)/(?P<admin_key>.+)/$', views.ResultsView.as_view(), name='detail'),
        url(r'^create/$', views.CreateView.as_view(), name='create')
        )

doodle/poll/forms.py
from django import forms
from poll.models import Poll, Time, Option
from django.forms.models import formset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, Field, HTML

choices = ( (1,'Yes'),
            (0,'No'),
          )

class PollForm(forms.ModelForm):
    title = forms.CharField(
        max_length=128,
        widget=forms.TextInput(attrs={'placeholder':"Name of Poll"}),
        label='Name of the Poll'
    )

    creator = forms.EmailField(
        max_length=254,
        widget=forms.TextInput(attrs={'placeholder':"Email"}),
        label='Email'
    )

    creator_name = forms.CharField(
        max_length=128,
        widget=forms.TextInput(attrs={'placeholder':"Your Name"}),
        label='Your Name'
    )

    location = forms.CharField(
        max_length=128,
        widget=forms.TextInput(attrs={'placeholder':"Location"}),
        label='Location'
    )

    description = forms.CharField(
        max_length=128,
        widget=forms.TextInput(attrs={'placeholder':"Description"}),
        label='Description'
    )

    hidden = forms.TypedChoiceField(
        choices=choices,
        widget=forms.RadioSelect, coerce=int,
        label='Do you want this poll to be private?'
    )

    one_option = forms.TypedChoiceField(
        choices=choices,
        widget=forms.RadioSelect,
        coerce=int,
        label='Can participants only choose one option?'
    )

    participants_option = forms.IntegerField(
        label='Max number of participants per option. Not required.',
        required=False
    )

    def __init__(self, *args, **kwargs):
        if kwargs.has_key('update'):
            update = kwargs.pop('update')
            adminHash = kwargs.pop('adminHash')
            pk = kwargs.pop('pk')
        else:
            update = False
        super(PollForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'poll_form'
        self.helper.form_method = 'post'
        if update:
            self.helper.form_action = '/poll/' + str(pk) + '/edit/' + adminHash + '/'
        else:
            self.helper.form_action = '/poll/create/'

        self.helper.add_input(Submit('submit', 'Submit'))

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Poll
        exclude = ('admin_hash',)

    def clean(self):
        cleaned_input = self.cleaned_data
        participants = cleaned_input.get('participants_option')
        if not(participants > 0):
            participants = -1
            cleaned_input['participants_option'] = participants
        return cleaned_input

class TimeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TimeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'poll_form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))


    class Meta:
        # Provide an association between the ModelForm and a model
        exclude = ('poll_id',)
        model = Time

class OptionForm(forms.ModelForm):
    time_id = forms.ModelMultipleChoiceField(
        queryset=Time.objects.all(),
        required=True,
        widget=forms.CheckboxSelectMultiple
    )
    user = forms.CharField()
    anonymous = forms.TypedChoiceField(
        choices=choices,
        widget=forms.RadioSelect,
        coerce=int,
        help_text="Do you wish to be anonymous?"
    )

    def __init__(self, fk, *args, **kwargs):
        super(OptionForm, self).__init__(*args, **kwargs)
        # Filter the options based on the foreign key
        self.fields['time_id'].queryset = Time.objects.filter(poll_id=fk)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Option

TimeFormSet = formset_factory(TimeForm, can_delete=True, extra=5)

class TimeFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(TimeFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.render_required_fields = True,
        self.layout = Layout(
            Field('time', id="time-field", css_class="timefields")
        )
        self.add_input(Submit("submit", "Save"))

doodle/poll/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
#from django.template import RequestContext
from django.http import HttpResponseRedirect
from poll.models import Poll, Time, Option
from poll.forms import OptionForm, PollForm, TimeFormSet, TimeFormSetHelper
from django.views import generic
from django.views.generic.base import View
import hashlib
import time


class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'poll_list'
    error_template_name = 'poll/error.html'

    def get_queryset(self):
        return Poll.objects.filter(hidden=False).order_by('title')

class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'poll/results.html'
    error_template_name = 'poll/error.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        poll = get_object_or_404(Poll, pk=pk)
        if  'admin_key' in self.kwargs:
            admin_key = self.kwargs['admin_key']
        else:
            admin_key = ""
        if poll.hidden and poll.admin_hash != admin_key:
            return render(request, self.error_template_name, {'message': "Admin Key doesn't matches"})
        else:
            options = poll.get_all_options()
            days = poll.get_days_times()
            votes = poll.get_participants_times()
            return render(request, self.template_name, {'poll': poll, 'options': options, 'days': days, "votes": votes})

class VoteView(View):
    form_class = OptionForm
    template_name = 'poll/vote.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        poll = get_object_or_404(Poll, pk=pk)
        form = self.form_class(pk)
        return render(request, self.template_name, {'form': form, "poll": poll})

    def post(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        poll = get_object_or_404(Poll, pk=self.kwargs['pk'])
        form = self.form_class(poll.id, request.POST)
        if form.is_valid() and self.constraints_met(poll, form):
            form.save(commit=True)
            return HttpResponseRedirect('/poll/' + str(poll.id))
        return render(request, self.template_name, {'form': form, "poll": poll})

    def constraints_met(self, poll, form):
        options = poll.get_all_options();
        votes = {}
        form = form.cleaned_data
        options_picked = 0;
        max_participants = poll.participants_option
        constraints_met = True

        # Check that only one time has been picked
        if poll.one_option and 'time_id' in form:
            options_picked = form['time_id'].count()
            constraints_met = constraints_met and (options_picked == 1)

        # Check if max number participants reached
        if max_participants > -1:
            for time in form['time_id']:
                current_particiapnts = Option.objects.filter(time_id=time.id).count()
                constraints_met = constraints_met and (current_particiapnts < max_participants)
        return constraints_met

class CreateView(generic.CreateView):
    form_class = PollForm
    model = Poll
    template_name = 'poll/create.html'
    success_url = '/poll/'

    def get(self, request, *args, **kwargs):
        '''
        Function to handle get requests and generate form and formset
        '''
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(form=form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        '''
        Function that handles post requests. Tests if the poll and form times are
        valid.
        '''
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        '''
        Function that is called if a form is valid. Saves the poll and redirects to the
        success page.
        '''
        self.object = form.save(commit=False)
        # Generate hash for admin url using form data and current time, ugly but does the job
        hash = hashlib.sha256()
        form_string = str(form)
        current_time = str(time.time())
        hash.update(form_string + current_time)
        self.object.admin_hash = hash.hexdigest()
        self.object.save()
        response_url = self.get_success_url() + str(self.object.id) + "/addTime/" +  self.object.admin_hash
        return HttpResponseRedirect(response_url)

    def form_invalid(self, form):
        '''
        Function that is called if a form is invlaid. reloads the form page.
        '''
        context = self.get_context_data(form=form)
        return self.render_to_response(context, status=400)

class AddTimeView(generic.CreateView):
    form_class = TimeFormSet
    form_helper = TimeFormSetHelper
    model = Time
    template_name = 'poll/addTime.html'
    success_url = '/poll/'
    error_template_name = 'poll/error.html'

    def get(self, request, *args, **kwargs):
        '''
        Function to handle get requests and generate form and formset
        '''
        pk = self.kwargs['pk']
        admin_key = self.kwargs['admin_key']
        self.object = None
        poll = get_object_or_404(Poll, pk=pk)
        if poll.admin_hash == admin_key:
            formset = self.form_class()
            helper = self.form_helper()
            context = self.get_context_data(formset=formset, helper=helper)
            return self.render_to_response(context)
        else:
            return render(request, self.error_template_name, {'message': "Admin Key doesn't matches"})

    def post(self, request, *args, **kwargs):
        '''
        Function that handles post requests. Tests if the poll and form times are
        valid.
        '''
        pk = self.kwargs['pk']
        admin_key = self.kwargs['admin_key']
        self.object = None
        poll = get_object_or_404(Poll, pk=pk)
        if poll.admin_hash == admin_key:
            form = self.form_class(self.request.POST)
            if form.is_valid() and self.form_contains_time(form):
                return self.form_valid(form, poll)
            else:
                return self.form_invalid(form)
        else:
            return render(request, self.error_template_name, {'message': "Admin Key doesn't matches"})

    def form_valid(self, formset, poll):
        '''
        Function that is called if a form is valid. Saves the poll and redirects to the
        success page.
        '''
        for form in formset.cleaned_data:
            if 'time' in form:
                time = Time(time = form['time'])
                time.poll_id = poll
                self.object = time.save()
        response_url = self.success_url
        return HttpResponseRedirect(response_url)

    def form_invalid(self, form):
        '''
        Function that is called if a form is invlaid. reloads the form page.
        '''
        helper = self.form_helper()
        context = self.get_context_data(formset=form, helper=helper)
        return self.render_to_response(context, status=400)

    def form_contains_time(self, formset):
        for form in formset.cleaned_data:
            if 'time' in form:
                return True
        return False

class EditView(generic.UpdateView):
    model = Poll
    form_class = PollForm
    success_url = '/poll/'
    template_name = 'poll/create.html'
    error_template_name = 'poll/error.html'

    def get(self, request, *args, **kwargs):
        self.object = None
        pk = self.kwargs['pk']
        admin_key = self.kwargs['admin_key']
        poll = get_object_or_404(Poll, pk=pk)
        if poll.admin_hash == admin_key:
            form = self.form_class(instance=poll, update=True, pk=poll.id, adminHash=admin_key)
            context = self.get_context_data(form=form)
            return self.render_to_response(context)
        else:
            return render(request, self.error_template_name, {'message': "Admin Key doesn't matches"})


    def post(self, request, *args, **kwargs):
        self.object = None
        pk = self.kwargs['pk']
        admin_key = self.kwargs['admin_key']
        poll = get_object_or_404(Poll, pk=pk)
        if poll.admin_hash == admin_key:
            form = self.form_class(self.request.POST, instance=poll)
            if form.is_valid():
                return self.form_valid(form, poll)
            else:
                return self.form_invalid(form)
        else:
            return render(request, self.error_template_name, {'message': "Admin Key doesn't matches"})

    def form_valid(self, form, poll):
        '''
        Function that is called if a form is valid. Saves the poll and redirects to the
        success page.
        '''
        self.object = form.save()
        response_url = self.get_success_url() + str(poll.id) + "/addTime/" +  poll.admin_hash
        return HttpResponseRedirect(response_url)

    def form_invalid(self, form):
        '''
        Function that is called if a form is invlaid. reloads the form page.
        '''
        context = self.get_context_data(form=form)
        return self.render_to_response(context, status=400)

doodle/templates/poll/addTime.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add a Time now{% endblock %}

{% block body_block %}
<div>

        <h1 align="middle">Add a Time now</h1>
                {% crispy formset helper %}
                <button id="add_time">Add another time</button>
                <h1 class = "home_page_heading">By Trinity , For Trinity ©</h1>
</div>

{% endblock %}

doodle/templates/poll/create.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add a Poll now{% endblock %}

{% block body_block %}
        <div class = "create_poll">

        <h1 align="middle">Add a Poll now</h1>
              
                {% crispy form form.helper %}


</div>
<h1 class = "home_page_heading">By Trinity , For Trinity ©</h1>
{% endblock %}

doodle/templates/poll/edit.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit a Poll now{% endblock %}

{% block body_block %}
<div>
        <h1>Edit</h1>
        {{ message }}
</div>
{% endblock %}

doodle/templates/poll/error.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit a Poll now{% endblock %}

{% block body_block %}
<div>
        <h1>Error</h1>
        {{ message }}
</div>
{% endblock %}

doodle/templates/poll/index.html
{% extends 'base/base.html' %}
{% block title %}Poll Index{% endblock %}

{% block body_block %}
<h1 class="title">Poll List</h1>



{% if poll_list %}
<div class = "poll_index_buttons">
{% for poll in poll_list %}
<a href="{% url 'poll:detail' poll.pk %}"><li class="poll_buttons">{{ poll.title }}</li></a>
{% endfor %}
<a class="poll_index_new" href="/poll/create/" position="relative">Create a poll</a>

</div>

{% else %}
<p align="center">No polls created at this time<p>
<a class="poll_index_new" href="/poll/create/" position="relative">Create a poll</a>

{% endif %}
</div>

</div>
<h1 class = "home_page_heading">By Trinity , For Trinity ©</h1>

{% endblock %}

doodle/templates/poll/results.html
{% extends 'base/base.html' %}
{% block title %}{{ poll.title }}{% endblock %}
{% block body_block %}
<h1 class="title">{{ poll.title }}</h1>
<h2> Location : {{ poll.location }}</h2>
<h3 id="cap"> Descrption : {{ poll.description }}</h3>

<table width="205" height="82">

         <tr>
                <td class="timetable_head">Participant</td>
        {% for key, values in days.items %}
                <th colspan="{{ values|length }}" class="timetable_head">{{key}}</th>

        {% endfor %}
               <tr>
           <td class="timetable_head"></td>


        {% for key, values in days.items %}
                {% for value in values %}
                     <th class="timetable_head">{{value}}</th>
                {% endfor %}

        {% endfor %}
           </tr>
  <!--    {% for key, values in days.items %}
            <tr>
                <td>Participant</td>
                {% for value in values %}
                    <td>{{value}}</td>
                {% endfor %}
            </tr>
        {% endfor %}-->
        {% for key, values in votes.items %}
            <tr>

                <td class="timetable_name">
                    {% if key.anonymous %}
                    Anonymous
                    {% else %}
                    {{key}}
                    {% endif %}
                </td>
                {% for value in values %}
                  {% if value %}
                    <td class="chosen" ></td>
                    {% else %}
                    <td align="center"> Free Slot  </td>

                    {% endif %}

                {% endfor %}
            </tr>
        {% endfor %}
    <td class="poll_vote_button"> <a href="{% url 'poll:vote' poll.id %}">Vote</a></td>
</table>

<h1 class = "home_page_heading">By Trinity , For Trinity ©</h1>

{% endblock %}

doodle/templates/poll/vote.html
{% extends 'base/base.html' %}
{% block title %}{{ poll.title }}{% endblock %}

{% block body_block %}
    <h1>Vote on Poll {{ poll.title }}</h1>
    
    <form id="poll_form" method="post" action="/poll/{{ poll.id }}/vote/" class = "vote_align_page">

        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
       <!--<p class = "vote_page_align">-->
            <p >
            {{ field.errors }}
            {{ field.help_text}}
            {{ field }}
        </p>
        <!--</p>-->
        {% endfor %}

        <input type="submit" name="submit" value="Vote" />
    </form>
    <h1 class = "home_page_heading">By Trinity , For Trinity ©</h1>
{% endblock %}